# Logging configuration
log_level: "debug,mq_bridge=trace"
logger: "plain"

routes:
  http_to_file:
    input:
      http:
        url: "127.0.0.1:3000"
        response_out:
          static: "Hello, bridge!"
    output:
      file: "output.txt"
